/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary, #3b82f6)',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary, #6b7280)',
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        neutral: {
          DEFAULT: 'var(--color-neutral, #9ca3af)',
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        semantic: {
          DEFAULT: 'var(--color-semantic, #f59e0b)',
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
          800: '#854d0e',
          900: '#713f12',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        background: {
          DEFAULT: 'var(--color-background, #ffffff)',
        },
        surface: {
          DEFAULT: 'var(--color-surface, #f9fafb)',
        },
        text: {
          DEFAULT: 'var(--color-text, #111827)',
          secondary: 'var(--color-text-secondary, #6b7280)',
        },
      },
      maxWidth: {
        'screen-xl': '1024px',
        'screen-2xl': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: 'var(--font-heading, Inter), system-ui, sans-serif',
        body: 'var(--font-body, Inter), system-ui, sans-serif',
      },
      spacing: {
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        button: 'var(--button-primary-border-radius, 0.375rem)',
        card: 'var(--card-border-radius, 0.5rem)',
        input: 'var(--input-border-radius, 0.375rem)',
      },
      boxShadow: {
        button: 'var(--button-primary-shadow, 0 1px 3px 0 rgba(0, 0, 0, 0.1))',
        card: 'var(--card-shadow, 0 1px 3px 0 rgba(0, 0, 0, 0.1))',
        'card-hover': 'var(--card-hover-shadow, 0 10px 25px -3px rgba(0, 0, 0, 0.1))',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [
    // Custom plugin for dynamic CSS variables
    function({ addUtilities, theme }) {
      const newUtilities = {
        '.btn-primary': {
          backgroundColor: 'var(--button-primary-background, #3b82f6)',
          color: 'var(--button-primary-text, #ffffff)',
          border: 'var(--button-primary-border, 1px solid #3b82f6)',
          borderRadius: 'var(--button-primary-border-radius, 0.375rem)',
          boxShadow: 'var(--button-primary-shadow, 0 1px 3px 0 rgba(0, 0, 0, 0.1))',
          padding: 'var(--button-primary-padding, 0.5rem 1rem)',
          fontSize: 'var(--button-primary-font-size, 0.875rem)',
          transition: 'all 0.15s ease-in-out',
          '&:hover': {
            backgroundColor: 'var(--button-primary-hover-background, #2563eb)',
            color: 'var(--button-primary-hover-text, #ffffff)',
            transform: 'var(--button-primary-hover-transform, translateY(-1px))',
            boxShadow: 'var(--button-primary-hover-shadow, 0 4px 6px -1px rgba(0, 0, 0, 0.1))',
          },
        },
        '.btn-secondary': {
          backgroundColor: 'var(--button-secondary-background, #6b7280)',
          color: 'var(--button-secondary-text, #ffffff)',
          border: 'var(--button-secondary-border, 1px solid #6b7280)',
          borderRadius: 'var(--button-secondary-border-radius, 0.375rem)',
          boxShadow: 'var(--button-secondary-shadow, none)',
          padding: 'var(--button-secondary-padding, 0.5rem 1rem)',
          fontSize: 'var(--button-secondary-font-size, 0.875rem)',
          transition: 'all 0.15s ease-in-out',
          '&:hover': {
            backgroundColor: 'var(--button-secondary-hover-background, #4b5563)',
            color: 'var(--button-secondary-hover-text, #ffffff)',
            transform: 'var(--button-secondary-hover-transform, translateY(-1px))',
            boxShadow: 'var(--button-secondary-hover-shadow, 0 4px 6px -1px rgba(0, 0, 0, 0.1))',
          },
        },
        '.card': {
          backgroundColor: 'var(--card-background, #ffffff)',
          border: '1px solid var(--card-border-color, #e5e7eb)',
          borderRadius: 'var(--card-border-radius, 0.5rem)',
          boxShadow: 'var(--card-shadow, 0 1px 3px 0 rgba(0, 0, 0, 0.1))',
          transition: 'all 0.2s ease-in-out',
          '&:hover': {
            transform: 'var(--card-hover-transform, translateY(-2px))',
            boxShadow: 'var(--card-hover-shadow, 0 10px 25px -3px rgba(0, 0, 0, 0.1))',
          },
        },
        '.input': {
          backgroundColor: 'var(--input-background, #ffffff)',
          border: '1px solid var(--input-border-color, #d1d5db)',
          borderRadius: 'var(--input-border-radius, 0.375rem)',
          padding: '0.5rem 0.75rem',
          fontSize: '0.875rem',
          transition: 'border-color 0.15s ease-in-out',
          '&:focus': {
            outline: 'none',
            borderColor: 'var(--color-primary, #3b82f6)',
            boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
          },
        },
      };
      addUtilities(newUtilities);
    },
  ],
} 